# Personal Knowledge Decay Predictor

## Notebook 01
# Data Understanding and Dataset Audit

### Objective
The purpose of this notebook is to understand the educational dataset, inspect its quality, identify useful features, detect missing values, analyze data distributions, and prepare a roadmap for preprocessing.

---
Author : Tushar Kacha , Isha Kakadiya
Project : Personal Knowledge Decay Predictor

# Step 1
## Import Required Libraries

### Why?

Before reading and analyzing the dataset, we need Python libraries for:

- Data manipulation
- Numerical computation
- Visualization
- File handling

In [1]:
# Data manipulation
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt

# File handling
import os
import glob
from pathlib import Path

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries Imported Successfully")

Libraries Imported Successfully

# Step 2

## Mount Google Drive

### Why?

The dataset is stored in Google Drive.

Mounting Google Drive allows Colab to directly access the project files.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Step 3

## Set Project Directory

### Why?

Instead of writing long file paths repeatedly, we define one project directory.

This makes the notebook portable and easier to maintain.

In [3]:
import sys
from pathlib import Path

PROJECT_NAME = "Personal Knowledge Decay Predictor"

matches = [
    p for p in Path("/content/drive/MyDrive").rglob(PROJECT_NAME)
    if p.is_dir()
]

PROJECT_ROOT = matches[0]

sys.path.append(str(PROJECT_ROOT))

from config import *

✅ Project Root : /content/drive/MyDrive/Personal Knowledge Decay Predictor

# Step 4

## Explore Project Structure

Before loading any dataset, verify that all project folders are available.

In [4]:
import os

for root, dirs, files in os.walk("Data/Raw"):
    print(root)
    for f in files[:5]:  # show first 5 files
        print("   ", f)

Data/Raw
Data/Raw/Competition Training Set
    student_log_10.csv
    student_log_1.csv
    student_log_2.csv
    student_log_3.csv
    validation_test_label.csv
Data/Raw/Released Full Dataset
    anonymized_full_release_competition_dataset.csv

# Step 5

# Locate All Dataset Files

## Why?

The datasets are distributed across multiple folders and files.

Instead of manually loading each file, we will automatically discover all CSV and TXT files. This makes our notebook reusable and robust.

In [5]:
from pathlib import Path

DATA_PATH = Path("Data/Raw")

csv_files = list(DATA_PATH.rglob("*.csv"))
txt_files = list(DATA_PATH.rglob("*.txt"))
tsv_files = list(DATA_PATH.rglob("*.tsv"))

print("="*60)
print("CSV Files :", len(csv_files))
print("TXT Files :", len(txt_files))
print("TSV Files :", len(tsv_files))
print("="*60)

for file in csv_files:
    print(file)

============================================================
CSV Files : 13
TXT Files : 0
TSV Files : 0
============================================================
Data/Raw/Competition Training Set/student_log_10.csv
Data/Raw/Competition Training Set/student_log_1.csv
Data/Raw/Competition Training Set/student_log_2.csv
Data/Raw/Competition Training Set/student_log_3.csv
Data/Raw/Competition Training Set/validation_test_label.csv
Data/Raw/Competition Training Set/student_log_7.csv
Data/Raw/Competition Training Set/student_log_8.csv
Data/Raw/Competition Training Set/training_label.csv
Data/Raw/Competition Training Set/student_log_5.csv
Data/Raw/Competition Training Set/student_log_4.csv
Data/Raw/Competition Training Set/student_log_6.csv
Data/Raw/Competition Training Set/student_log_9.csv
Data/Raw/Released Full Dataset/anonymized_full_release_competition_dataset.csv

# Step 6

# Load the Main Dataset

We first identify the primary interaction dataset.

The interaction dataset contains the student-skill learning history that will be used throughout the project.

In [6]:
largest_csv = max(csv_files, key=lambda x: x.stat().st_size)

print("Main Dataset:")
print(largest_csv)

df = pd.read_csv(largest_csv)

print("\nDataset Loaded Successfully")

Main Dataset:
Data/Raw/Released Full Dataset/anonymized_full_release_competition_dataset.csv

Dataset Loaded Successfully

# Step 7

# Basic Dataset Information

The first step in understanding any dataset is to inspect:

- Number of rows
- Number of columns
- Data types
- Memory usage

In [7]:
print("="*60)
print("Dataset Shape")
print("="*60)

print(df.shape)

print()

print("="*60)
print("Data Types")
print("="*60)

df.info()

============================================================
Dataset Shape
============================================================
(942816, 82)

============================================================
Data Types
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 942816 entries, 0 to 942815
Data columns (total 82 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   studentId                               942816 non-null  int64
 1   MiddleSchoolId                          942816 non-null  int64
 2   InferredGender                          769160 non-null  object
 3   SY ASSISTments Usage                    942816 non-null  object
 4   AveKnow                                 942816 non-null  float64
 5   AveCarelessness                         942816 non-null  float64
 6   AveCorrect                              942816 non-null  float64
 7   NumActions                              942816 non-null  int64
 8   AveResBored                             942816 non-null  float64
 9   AveResEngcon                            942816 non-null  float64
 10  AveResConf                              942816 non-null  float64
 11  AveResFrust                             942816 non-null  float64
 12  AveResOfftask                           942816 non-null  float64
 13  AveResGaming                            942816 non-null  float64
 14  action_num                              942816 non-null  int64
 15  skill                                   942816 non-null  object
 16  problemId                               942816 non-null  int64
 17  problemType                             942816 non-null  object
 18  assignmentId                            942816 non-null  int64
 19  assistmentId                            942816 non-null  int64
 20  startTime                               942816 non-null  int64
 21  endTime                                 942816 non-null  int64
 22  timeTaken                               942816 non-null  float64
 23  correct                                 942816 non-null  int64
 24  original                                942816 non-null  int64
 25  hint                                    942816 non-null  int64
 26  hintCount                               942816 non-null  int64
 27  hintTotal                               942816 non-null  int64
 28  scaffold                                942816 non-null  int64
 29  bottomHint                              942816 non-null  int64
 30  attemptCount                            942816 non-null  int64
 31  frIsHelpRequest                         942816 non-null  int64
 32  frPast5HelpRequest                      942816 non-null  int64
 33  frPast8HelpRequest                      942816 non-null  int64
 34  stlHintUsed                             942816 non-null  int64
 35  past8BottomOut                          942816 non-null  int64
 36  totalFrPercentPastWrong                 942816 non-null  float64
 37  totalFrPastWrongCount                   942816 non-null  int64
 38  frPast5WrongCount                       942816 non-null  int64
 39  frPast8WrongCount                       942816 non-null  int64
 40  totalFrTimeOnSkill                      942816 non-null  float64
 41  timeSinceSkill                          942816 non-null  float64
 42  frWorkingInSchool                       942816 non-null  int64
 43  totalFrAttempted                        942816 non-null  int64
 44  totalFrSkillOpportunities               942816 non-null  int64
 45  responseIsFillIn                        942816 non-null  int64
 46  responseIsChosen                        942816 non-null  int64
 47  endsWithScaffolding                     942816 non-null  int64
 48  endsWithAutoScaffolding                 942816 non-null  int64
 49  frTimeTakenOnScaffolding                942816 non-null  float64
 50  frTotalSkillOpportunitiesScaffolding    942816 non-null  int64
 51  totalFrSkillOpportunitiesByScaffolding  942816 non-null  float64
 52  frIsHelpRequestScaffolding              942816 non-null  int64
 53  timeGreater5Secprev2wrong               942816 non-null  int64
 54  sumRight                                942816 non-null  int64
 55  helpAccessUnder2Sec                     942816 non-null  int64
 56  timeGreater10SecAndNextActionRight      942816 non-null  int64
 57  consecutiveErrorsInRow                  942816 non-null  int64
 58  sumTime3SDWhen3RowRight                 942731 non-null  float64
 59  sumTimePerSkill                         942816 non-null  float64
 60  totalTimeByPercentCorrectForskill       942816 non-null  float64
 61  Prev5count                              942816 non-null  int64
 62  timeOver80                              942816 non-null  int64
 63  manywrong                               942816 non-null  int64
 64  confidence(BORED)                       942816 non-null  float64
 65  confidence(CONCENTRATING)               942816 non-null  float64
 66  confidence(CONFUSED)                    942816 non-null  float64
 67  confidence(FRUSTRATED)                  942816 non-null  float64
 68  confidence(OFF TASK)                    942816 non-null  float64
 69  confidence(GAMING)                      942816 non-null  float64
 70  RES_BORED                               942816 non-null  float64
 71  RES_CONCENTRATING                       942816 non-null  float64
 72  RES_CONFUSED                            942816 non-null  float64
 73  RES_FRUSTRATED                          942816 non-null  float64
 74  RES_OFFTASK                             942816 non-null  float64
 75  RES_GAMING                              942816 non-null  float64
 76  Ln-1                                    942816 non-null  object
 77  Ln                                      942816 non-null  object
 78  MCAS                                    942816 non-null  int64
 79  Enrolled                                942816 non-null  int64
 80  Selective                               942816 non-null  int64
 81  isSTEM                                  316974 non-null  float64
dtypes: float64(31), int64(45), object(6)
memory usage: 589.8+ MB

# Step 8

# Display Sample Records

Viewing the first few rows helps us understand:

- Feature names
- Data format
- Missing values
- Timestamp format

In [8]:
df.head()

,studentId,MiddleSchoolId,InferredGender,SY ASSISTments Usage,AveKnow,AveCarelessness,AveCorrect,NumActions,AveResBored,AveResEngcon,AveResConf,AveResFrust,AveResOfftask,AveResGaming,action_num,skill,problemId,problemType,assignmentId,assistmentId,startTime,endTime,timeTaken,correct,original,hint,hintCount,hintTotal,scaffold,bottomHint,attemptCount,frIsHelpRequest,frPast5HelpRequest,frPast8HelpRequest,stlHintUsed,past8BottomOut,totalFrPercentPastWrong,totalFrPastWrongCount,frPast5WrongCount,frPast8WrongCount,totalFrTimeOnSkill,timeSinceSkill,frWorkingInSchool,totalFrAttempted,totalFrSkillOpportunities,responseIsFillIn,responseIsChosen,endsWithScaffolding,endsWithAutoScaffolding,frTimeTakenOnScaffolding,frTotalSkillOpportunitiesScaffolding,totalFrSkillOpportunitiesByScaffolding,frIsHelpRequestScaffolding,timeGreater5Secprev2wrong,sumRight,helpAccessUnder2Sec,timeGreater10SecAndNextActionRight,consecutiveErrorsInRow,sumTime3SDWhen3RowRight,sumTimePerSkill,totalTimeByPercentCorrectForskill,Prev5count,timeOver80,manywrong,confidence(BORED),confidence(CONCENTRATING),confidence(CONFUSED),confidence(FRUSTRATED),confidence(OFF TASK),confidence(GAMING),RES_BORED,RES_CONCENTRATING,RES_CONFUSED,RES_FRUSTRATED,RES_OFFTASK,RES_GAMING,Ln-1,Ln,MCAS,Enrolled,Selective,isSTEM
0,8,2,Male,2004-2005,0.352416,0.183276,0.483902,1056,0.208389,0.679126,0.115905,0.112408,0.156503,0.196561,9950,properties-of-geometric-figures,1118,textfieldquestion,20405010,104051118,1096470301,1096470350,49.0,0,1,1,1,1,0,0,1,1,0,0,0,0,0.0,0,0,0,0.0,0.0,1,0,0,0,0,0,0,0.0,0,0.0,0,0,0,0,0,0,0.0,49.0,0.000000,0,0,0,0.597865,0.234294,0.0000,0.0,0.838710,0.008522,0.376427,0.320317,0.000000,0.0,0.785585,0.000264,0.13,0.06119,45,0,0,NaN
1,8,2,Male,2004-2005,0.352416,0.183276,0.483902,1056,0.208389,0.679126,0.115905,0.112408,0.156503,0.196561,9951,properties-of-geometric-figures,1119,noprobtype,20405010,104051119,1096470350,1096470354,4.0,1,0,0,0,0,1,0,1,1,1,1,0,0,0.0,0,0,0,49.0,0.0,1,1,1,0,0,1,0,4.0,0,0.0,1,0,1,0,1,0,0.0,53.0,106.000000,1,0,0,0.355694,0.992585,0.9375,0.0,0.600000,0.047821,0.156027,0.995053,0.887452,0.0,0.468252,0.001483,0.06119,0.21351,45,0,0,NaN
2,8,2,Male,2004-2005,0.352416,0.183276,0.483902,1056,0.208389,0.679126,0.115905,0.112408,0.156503,0.196561,9952,sum-of-interior-angles-more-than-3-sides,1120,noprobtype,20405010,104051120,1096470354,1096470360,6.0,0,0,0,0,0,0,0,1,0,0,0,0,0,0.0,0,0,0,0.0,0.0,1,2,0,0,0,0,0,6.0,0,0.0,0,0,1,0,0,0,0.0,6.0,0.000000,2,0,0,0.355694,0.992585,0.9375,0.0,0.600000,0.047821,0.156027,0.995053,0.887452,0.0,0.468252,0.001483,0.116,0.033306,45,0,0,NaN
3,8,2,Male,2004-2005,0.352416,0.183276,0.483902,1056,0.208389,0.679126,0.115905,0.112408,0.156503,0.196561,9953,sum-of-interior-angles-more-than-3-sides,1120,noprobtype,20405010,104051120,1096470360,1096470378,18.0,0,0,0,0,0,0,0,2,0,0,0,0,0,0.0,1,0,0,0.0,0.0,1,3,1,0,0,0,0,6.0,1,0.0,0,0,1,0,0,1,0.0,24.0,0.000000,3,0,0,0.355694,0.617065,0.0000,0.0,0.204082,0.343996,0.156027,0.744520,0.000000,0.0,0.108417,0.010665,0.116,0.033306,45,0,0,NaN
4,8,2,Male,2004-2005,0.352416,0.183276,0.483902,1056,0.208389,0.679126,0.115905,0.112408,0.156503,0.196561,9954,sum-of-interior-angles-more-than-3-sides,1121,noprobtype,20405010,104051121,1096470378,1096470380,2.0,1,0,0,0,1,0,0,1,0,0,0,0,0,1.0,1,1,1,6.0,0.0,1,3,1,0,0,0,0,2.0,1,1.0,0,0,2,0,1,0,0.0,26.0,77.999999,4,0,1,0.355694,0.617065,0.0000,0.0,0.204082,0.343996,0.156027,0.744520,0.000000,0.0,0.108417,0.010665,0.033306,0.118386,45,0,0,NaN

In [9]:
df.sample(5, random_state=42)

,studentId,MiddleSchoolId,InferredGender,SY ASSISTments Usage,AveKnow,AveCarelessness,AveCorrect,NumActions,AveResBored,AveResEngcon,AveResConf,AveResFrust,AveResOfftask,AveResGaming,action_num,skill,problemId,problemType,assignmentId,assistmentId,startTime,endTime,timeTaken,correct,original,hint,hintCount,hintTotal,scaffold,bottomHint,attemptCount,frIsHelpRequest,frPast5HelpRequest,frPast8HelpRequest,stlHintUsed,past8BottomOut,totalFrPercentPastWrong,totalFrPastWrongCount,frPast5WrongCount,frPast8WrongCount,totalFrTimeOnSkill,timeSinceSkill,frWorkingInSchool,totalFrAttempted,totalFrSkillOpportunities,responseIsFillIn,responseIsChosen,endsWithScaffolding,endsWithAutoScaffolding,frTimeTakenOnScaffolding,frTotalSkillOpportunitiesScaffolding,totalFrSkillOpportunitiesByScaffolding,frIsHelpRequestScaffolding,timeGreater5Secprev2wrong,sumRight,helpAccessUnder2Sec,timeGreater10SecAndNextActionRight,consecutiveErrorsInRow,sumTime3SDWhen3RowRight,sumTimePerSkill,totalTimeByPercentCorrectForskill,Prev5count,timeOver80,manywrong,confidence(BORED),confidence(CONCENTRATING),confidence(CONFUSED),confidence(FRUSTRATED),confidence(OFF TASK),confidence(GAMING),RES_BORED,RES_CONCENTRATING,RES_CONFUSED,RES_FRUSTRATED,RES_OFFTASK,RES_GAMING,Ln-1,Ln,MCAS,Enrolled,Selective,isSTEM
326475,3815,4,Male,2004-2005,0.235485,0.126368,0.370787,445,0.204611,0.692921,0.040441,0.112320,0.152805,0.293008,816283,order-of-operations,517,1,20405062,104050517,1114793566,1114793619,53.0,0,1,0,0,0,0,0,1,0,0,0,0,0,0.000000,0,0,0,0.0,0.0,1,169,0,0,0,0,0,0.000000,0,0.0,0,0,132,0,0,0,0.0,53.000000,0.000000,5,0,1,0.597865,0.374317,0.378151,0.000000,0.230769,0.343996,0.376427,0.511752,0.060808,0.000000,0.122595,0.010665,0.175,0.061371,46,1,0,NaN
857037,6292,3,Male,2005-2006,0.306077,0.130176,0.591133,203,0.270700,0.651728,0.063997,0.100411,0.260616,0.011793,5149638,algebraic-manipulation,474,interfaceradioquestion,723,474,1138124388,1138124487,99.0,1,1,0,0,0,0,0,1,0,0,0,0,0,0.000000,1,0,0,0.0,0.0,1,76,1,0,0,0,0,0.000000,0,0.0,0,0,63,0,1,0,0.0,266.000001,532.000001,5,1,0,0.355694,0.405535,0.000000,0.091463,0.578947,0.186970,0.156027,0.554432,0.000000,0.009561,0.440265,0.005797,0.041502,0.143184,44,0,0,NaN
255614,2895,2,Female,2004-2005,0.097265,0.058813,0.274493,1184,0.193372,0.687001,0.040304,0.144321,0.102802,0.443364,742081,probability,743,1,20405091,104050743,1099499919,1099499922,3.0,1,1,0,0,0,0,0,1,0,2,2,0,0,0.333333,1,1,1,28.0,0.0,1,126,3,0,0,0,0,0.000000,0,0.0,0,0,95,0,0,0,0.0,166.000000,498.000001,5,0,1,0.355694,0.656535,0.000000,0.000000,0.090909,0.558723,0.156027,0.770852,0.000000,0.000000,0.048295,0.152349,0.012031563,0.045006659,15,0,0,0.0
140619,2070,4,NaN,2004-2005,0.087325,0.055550,0.246546,941,0.203423,0.684094,0.051733,0.109100,0.119759,0.415518,673600,inequality-solving,230,noprobtype,20405041,104050230,1112980482,1112980491,9.0,0,0,1,1,3,0,0,1,1,1,1,0,1,0.000000,0,0,0,2.0,0.0,1,218,1,0,0,1,0,9.000000,1,1.0,1,0,150,0,0,0,0.0,30.000000,150.000000,5,0,1,0.597865,0.414661,0.000000,0.000000,0.230769,0.000297,0.376427,0.566909,0.000000,0.000000,0.122595,0.000009,0.042871,0.042219,21,1,0,NaN
146961,2157,4,Female,2004-2005,0.116171,0.075536,0.293893,1572,0.193569,0.682218,0.079234,0.128995,0.101616,0.369807,679942,probability,745,algebra,20405093,104050745,1106322396,1106322397,1.0,0,0,1,5,5,0,1,5,0,3,6,0,0,0.392857,11,2,2,325.0,0.0,1,287,29,1,0,1,0,3.999999,15,2.0,1,0,220,1,0,0,0.0,694.000000,2685.478263,5,0,1,0.355694,0.708783,0.000000,0.000000,0.090909,0.897696,0.156027,0.805711,0.000000,0.000000,0.048295,0.803484,0.011664,0.011664,14,0,0,NaN

# Step 9

# Statistical Summary

This provides an overview of numerical features.

In [10]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
studentId,942816.0,3.844844e+03,2.250484e+03,8.000000e+00,1.952000e+03,3.766000e+03,5.781000e+03,7.783000e+03
MiddleSchoolId,942816.0,2.515472e+00,1.039785e+00,1.000000e+00,2.000000e+00,2.000000e+00,4.000000e+00,4.000000e+00
AveKnow,942816.0,1.951549e-01,1.164510e-01,2.805683e-02,1.105422e-01,1.592854e-01,2.477041e-01,7.524983e-01
AveCarelessness,942816.0,1.094359e-01,5.995173e-02,7.801469e-03,6.875998e-02,9.451285e-02,1.373164e-01,4.305759e-01
AveCorrect,942816.0,3.726814e-01,1.073666e-01,0.000000e+00,2.949886e-01,3.455750e-01,4.288225e-01,9.329897e-01
NumActions,942816.0,8.698506e+02,5.302107e+02,2.000000e+00,4.780000e+02,7.540000e+02,1.151000e+03,3.057000e+03
AveResBored,942816.0,2.329490e-01,3.063690e-02,1.708711e-01,2.090351e-01,2.303944e-01,2.520816e-01,4.408702e-01
AveResEngcon,942816.0,6.584415e-01,2.744015e-02,4.033094e-01,6.420602e-01,6.606690e-01,6.765881e-01,7.239903e-01
AveResConf,942816.0,9.893992e-02,3.478799e-02,5.074724e-03,7.638474e-02,9.635730e-02,1.192824e-01,4.024829e-01
AveResFrust,942816.0,1.314057e-01,3.887526e-02,0.000000e+00,1.072779e-01,1.275040e-01,1.505819e-01,5.434629e-01
AveResOfftask,942816.0,1.722123e-01,5.799171e-02,8.316657e-02,1.314666e-01,1.595983e-01,1.985329e-01,8.374023e-01
AveResGaming,942816.0,1.927031e-01,1.534552e-01,1.973921e-03,6.072438e-02,1.562449e-01,2.989138e-01,7.092001e-01
action_num,942816.0,1.849329e+06,1.726001e+06,9.950000e+03,7.221708e+05,9.578745e+05,2.722813e+06,6.355811e+06
problemId,942816.0,1.899719e+03,2.579213e+03,1.000000e+00,7.210000e+02,1.116000e+03,1.419000e+03,2.276100e+04
assignmentId,942816.0,1.198773e+07,1.434706e+07,2.000000e+00,7.230000e+02,2.040501e+07,2.040510e+07,1.000000e+09
assistmentId,942816.0,6.061572e+07,5.128829e+07,5.000000e+00,2.213000e+03,1.040504e+08,1.040511e+08,1.040515e+08
startTime,942816.0,1.120793e+09,1.940359e+07,1.095421e+09,1.103136e+09,1.112980e+09,1.138371e+09,1.180218e+09
endTime,942816.0,1.120793e+09,1.940354e+07,1.095421e+09,1.103136e+09,1.112980e+09,1.138371e+09,1.180218e+09
timeTaken,942816.0,2.974787e+01,7.201977e+01,0.000000e+00,5.000000e+00,1.100000e+01,3.000000e+01,9.999000e+03
correct,942816.0,3.726814e-01,4.835186e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
original,942816.0,2.642138e-01,4.409139e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
hint,942816.0,3.310254e-01,4.705824e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
hintCount,942816.0,1.218490e+00,1.980665e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,5.600000e+01
hintTotal,942816.0,1.953967e+00,2.929242e+00,0.000000e+00,0.000000e+00,1.000000e+00,3.000000e+00,5.600000e+01
scaffold,942816.0,3.857317e-01,4.867679e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
bottomHint,942816.0,6.279380e-02,2.425918e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
attemptCount,942816.0,2.673605e+00,2.929801e+00,1.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,9.100000e+01
frIsHelpRequest,942816.0,2.681043e-01,4.429724e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
frPast5HelpRequest,942816.0,1.947322e+00,1.712580e+00,0.000000e+00,0.000000e+00,2.000000e+00,3.000000e+00,5.000000e+00
frPast8HelpRequest,942816.0,2.575323e+00,2.457799e+00,0.000000e+00,0.000000e+00,2.000000e+00,4.000000e+00,8.000000e+00
stlHintUsed,942816.0,4.012448e-03,6.321671e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
past8BottomOut,942816.0,2.416781e-01,6.746130e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.000000e+00
totalFrPercentPastWrong,942816.0,2.278824e-01,2.714040e-01,0.000000e+00,0.000000e+00,1.666667e-01,3.333333e-01,1.000000e+00
totalFrPastWrongCount,942816.0,1.988008e+00,3.390149e+00,0.000000e+00,0.000000e+00,1.000000e+00,2.000000e+00,7.300000e+01
frPast5WrongCount,942816.0,7.193800e-01,8.326992e-01,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,5.000000e+00
frPast8WrongCount,942816.0,9.447496e-01,1.076276e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,8.000000e+00
totalFrTimeOnSkill,942816.0,3.762134e+02,6.893029e+02,0.000000e+00,3.700000e+01,1.400000e+02,3.960000e+02,1.166300e+04
timeSinceSkill,942816.0,4.850802e+05,2.075599e+06,-9.928014e+06,0.000000e+00,0.000000e+00,8.000000e+00,4.840000e+07
frWorkingInSchool,942816.0,9.745878e-01,1.573735e-01,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
totalFrAttempted,942816.0,1.933160e+02,1.648989e+02,0.000000e+00,6.700000e+01,1.510000e+02,2.760000e+02,1.378000e+03
totalFrSkillOpportunities,942816.0,8.381019e+00,1.199829e+01,0.000000e+00,2.000000e+00,4.000000e+00,1.000000e+01,2.210000e+02
responseIsFillIn,942816.0,2.313071e-02,1.503187e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
responseIsChosen,942816.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
endsWithScaffolding,942816.0,6.360849e-01,4.811249e-01,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
endsWithAutoScaffolding,942816.0,5.724341e-03,7.544255e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
frTimeTakenOnScaffolding,942816.0,2.406085e+01,7.166565e+01,0.000000e+00,0.000000e+00,8.000000e+00,2.300000e+01,9.999000e+03
frTotalSkillOpportunitiesScaffolding,942816.0,3.989371e+00,6.581897e+00,0.000000e+00,0.000000e+00,2.000000e+00,5.000000e+00,1.050000e+02
totalFrSkillOpportunitiesByScaffolding,942816.0,1.036189e+00,1.184489e+00,0.000000e+00,0.000000e+00,1.176471e+00,1.656250e+00,3.700000e+01
frIsHelpRequestScaffolding,942816.0,6.700470e-01,4.701960e-01,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
timeGreater5Secprev2wrong,942816.0,4.538850e-02,2.081548e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
sumRight,942816.0,1.459821e+02,1.243425e+02,0.000000e+00,5.000000e+01,1.130000e+02,2.100000e+02,9.620000e+02
helpAccessUnder2Sec,942816.0,5.567364e-02,2.292905e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
timeGreater10SecAndNextActionRight,942816.0,2.074137e-01,4.054546e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
consecutiveErrorsInRow,942816.0,1.553071e-01,8.856917e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.600000e+01
sumTime3SDWhen3RowRight,942731.0,8.704219e-02,1.619202e+00,-1.133208e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.270904e+01
sumTimePerSkill,942816.0,6.016656e+02,9.539007e+02,0.000000e+00,1.070000e+02,2.750000e+02,6.690000e+02,1.245900e+04
totalTimeByPercentCorrectForskill,942816.0,2.166144e+03,4.601436e+03,0.000000e+00,1.897366e+02,8.400000e+02,2.404500e+03,3.105900e+05
Prev5count,942816.0,4.972689e+00,3.152810e-01,0.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00
timeOver80,942816.0,8.132340e-02,2.733313e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
manywrong,942816.0,7.156380e-01,4.511102e-01,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
confidence(BORED),942816.0,4.369585e-01,1.207508e-01,3.556942e-01,3.556942e-01,3.556942e-01,5.978648e-01,6.809816e-01
confidence(CONCENTRATING),942816.0,5.400894e-01,1.830483e-01,6.500000e-07,3.743169e-01,5.676439e-01,6.591692e-01,1.000000e+00
confidence(CONFUSED),942816.0,1.344500e-01,2.928769e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
confidence(FRUSTRATED),942816.0,1.641144e-01,3.260570e-01,0.000000e+00,0.000000e+00,0.000000e+00,9.146342e-02,1.000000e+00
confidence(OFF TASK),942816.0,2.560056e-01,2.131771e-01,0.000000e+00,9.090909e-02,2.307692e-01,2.307692e-01,1.000000e+00
confidence(GAMING),942816.0,3.378880e-01,3.352919e-01,3.890000e-05,4.782060e-02,1.869705e-01,6.145824e-01,9.996759e-01
RES_BORED,942816.0,2.329490e-01,1.163714e-01,1.560266e-01,1.560266e-01,1.560266e-01,3.764275e-01,5.053129e-01
RES_CONCENTRATING,942816.0,6.584415e-01,1.734275e-01,8.890000e-07,5.117519e-01,7.115475e-01,7.726099e-01,1.000000e+00
RES_CONFUSED,942816.0,9.893992e-02,2.495047e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
RES_FRUSTRATED,942816.0,1.314057e-01,3.003514e-01,0.000000e+00,0.000000e+00,0.000000e+00,9.561398e-03,1.000000e+00
RES_OFFTASK,942816.0,1.722123e-01,2.169970e-01,0.000000e+00,4.829494e-02,1.225948e-01,1.225948e-01,1.000000e+00
RES_GAMING,942816.0,1.927031e-01,3.402322e-01,1.205790e-06,1.482562e-03,5.796569e-03,2.596484e-01,9.993774e-01
MCAS,942816.0,-9.598230e+01,3.328276e+02,-9.990000e+02,1.400000e+01,2.300000e+01,3.400000e+01,5.400000e+01
Enrolled,942816.0,6.411474e-01,4.796641e-01,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
Selective,942816.0,3.004340e-01,4.584470e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
isSTEM,316974.0,2.041776e-01,4.031000e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00

In [11]:
df.describe(include="object").T

                         count    unique                top    freq
InferredGender          769160         2               Male  407637
SY ASSISTments Usage    942816         2          2004-2005  544596
skill                   942816       102            noskill   78103
problemType             942816        16  textfieldquestion  264399
Ln-1                  942816.0  113622.0              0.095  4514.0
Ln                    942816.0  125282.0           0.011664  4634.0

# Step 10

# Feature Dictionary

Every feature should be understood before feature engineering.

This table will later help us decide:

- Which features to keep
- Which features to remove
- Which features may cause leakage

In [12]:
feature_summary = pd.DataFrame({
    "Feature": df.columns,
    "Data Type": df.dtypes.values,
    "Missing Values": df.isnull().sum().values,
    "Missing %": (df.isnull().mean()*100).round(2).values,
    "Unique Values": df.nunique().values
})

feature_summary

,Feature,Data Type,Missing Values,Missing %,Unique Values
0,studentId,int64,0,0.00,1709
1,MiddleSchoolId,int64,0,0.00,4
2,InferredGender,object,173656,18.42,2
3,SY ASSISTments Usage,object,0,0.00,2
4,AveKnow,float64,0,0.00,1709
5,AveCarelessness,float64,0,0.00,1709
6,AveCorrect,float64,0,0.00,1598
7,NumActions,int64,0,0.00,921
8,AveResBored,float64,0,0.00,1709
9,AveResEngcon,float64,0,0.00,1709
10,AveResConf,float64,0,0.00,1709
11,AveResFrust,float64,0,0.00,1709
12,AveResOfftask,float64,0,0.00,1709
13,AveResGaming,float64,0,0.00,1709
14,action_num,int64,0,0.00,942816
15,skill,object,0,0.00,102
16,problemId,int64,0,0.00,3162
17,problemType,object,0,0.00,16
18,assignmentId,int64,0,0.00,268
19,assistmentId,int64,0,0.00,2286
20,startTime,int64,0,0.00,665163
21,endTime,int64,0,0.00,663889
22,timeTaken,float64,0,0.00,9632
23,correct,int64,0,0.00,2
24,original,int64,0,0.00,2
25,hint,int64,0,0.00,2
26,hintCount,int64,0,0.00,57
27,hintTotal,int64,0,0.00,41
28,scaffold,int64,0,0.00,2
29,bottomHint,int64,0,0.00,2
30,attemptCount,int64,0,0.00,91
31,frIsHelpRequest,int64,0,0.00,2
32,frPast5HelpRequest,int64,0,0.00,6
33,frPast8HelpRequest,int64,0,0.00,9
34,stlHintUsed,int64,0,0.00,2
35,past8BottomOut,int64,0,0.00,9
36,totalFrPercentPastWrong,float64,0,0.00,1717
37,totalFrPastWrongCount,int64,0,0.00,74
38,frPast5WrongCount,int64,0,0.00,6
39,frPast8WrongCount,int64,0,0.00,9
40,totalFrTimeOnSkill,float64,0,0.00,9251
41,timeSinceSkill,float64,0,0.00,52844
42,frWorkingInSchool,int64,0,0.00,2
43,totalFrAttempted,int64,0,0.00,1379
44,totalFrSkillOpportunities,int64,0,0.00,222
45,responseIsFillIn,int64,0,0.00,2
46,responseIsChosen,int64,0,0.00,1
47,endsWithScaffolding,int64,0,0.00,2
48,endsWithAutoScaffolding,int64,0,0.00,2
49,frTimeTakenOnScaffolding,float64,0,0.00,3511
50,frTotalSkillOpportunitiesScaffolding,int64,0,0.00,106
51,totalFrSkillOpportunitiesByScaffolding,float64,0,0.00,1462
52,frIsHelpRequestScaffolding,int64,0,0.00,2
53,timeGreater5Secprev2wrong,int64,0,0.00,2
54,sumRight,int64,0,0.00,963
55,helpAccessUnder2Sec,int64,0,0.00,2
56,timeGreater10SecAndNextActionRight,int64,0,0.00,2
57,consecutiveErrorsInRow,int64,0,0.00,57
58,sumTime3SDWhen3RowRight,float64,85,0.01,86477
59,sumTimePerSkill,float64,0,0.00,57028
60,totalTimeByPercentCorrectForskill,float64,0,0.00,378746
61,Prev5count,int64,0,0.00,6
62,timeOver80,int64,0,0.00,2
63,manywrong,int64,0,0.00,2
64,confidence(BORED),float64,0,0.00,3
65,confidence(CONCENTRATING),float64,0,0.00,46575
66,confidence(CONFUSED),float64,0,0.00,13
67,confidence(FRUSTRATED),float64,0,0.00,15
68,confidence(OFF TASK),float64,0,0.00,19
69,confidence(GAMING),float64,0,0.00,5736
70,RES_BORED,float64,0,0.00,4
71,RES_CONCENTRATING,float64,0,0.00,48944
72,RES_CONFUSED,float64,0,0.00,16
73,RES_FRUSTRATED,float64,0,0.00,19
74,RES_OFFTASK,float64,0,0.00,24
75,RES_GAMING,float64,0,0.00,6304
76,Ln-1,object,0,0.00,113622
77,Ln,object,0,0.00,125282
78,MCAS,int64,0,0.00,52
79,Enrolled,int64,0,0.00,2
80,Selective,int64,0,0.00,2
81,isSTEM,float64,625842,66.38,2

# Step 11

# Missing Value Analysis

Missing values can significantly affect machine learning performance.

We inspect both the count and percentage of missing values.

In [13]:
missing = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": (df.isnull().mean()*100)
})

missing = missing[missing["Missing Count"] > 0]

missing.sort_values(
    by="Missing Percentage",
    ascending=False
)

                         Missing Count  Missing Percentage
isSTEM                          625842           66.380078
InferredGender                  173656           18.418864
sumTime3SDWhen3RowRight             85            0.009016

# Step 12

# Duplicate Record Analysis

Duplicate interaction records may bias the learning model.

Therefore we inspect duplicate rows.

In [14]:
duplicates = df.duplicated().sum()

print("Duplicate Rows :", duplicates)

Duplicate Rows : 0

# Step 13

# Feature Categories

We now classify the features into:

- Numerical
- Categorical
- Datetime
- Boolean

In [15]:
numerical = df.select_dtypes(include=np.number).columns

categorical = df.select_dtypes(include="object").columns

print("Numerical Features :", len(numerical))
print("Categorical Features :", len(categorical))

Numerical Features : 76
Categorical Features : 6

In [16]:
from pathlib import Path

DATA_PATH = Path("Data/Raw")

for file in DATA_PATH.rglob("*"):
    if file.is_file():
        print(file)

Data/Raw/Competition Training Set/student_log_10.csv
Data/Raw/Competition Training Set/student_log_1.csv
Data/Raw/Competition Training Set/student_log_2.csv
Data/Raw/Competition Training Set/student_log_3.csv
Data/Raw/Competition Training Set/validation_test_label.csv
Data/Raw/Competition Training Set/student_log_7.csv
Data/Raw/Competition Training Set/student_log_8.csv
Data/Raw/Competition Training Set/training_label.csv
Data/Raw/Competition Training Set/student_log_5.csv
Data/Raw/Competition Training Set/student_log_4.csv
Data/Raw/Competition Training Set/student_log_6.csv
Data/Raw/Competition Training Set/student_log_9.csv
Data/Raw/Released Full Dataset/anonymized_full_release_competition_dataset.csv

In [17]:
DATASET_PATH = "Data/Raw/Released Full Dataset/anonymized_full_release_competition_dataset.csv"

df = pd.read_csv(DATASET_PATH)

print(df.shape)

(942816, 82)

In [18]:
df.head()

,studentId,MiddleSchoolId,InferredGender,SY ASSISTments Usage,AveKnow,AveCarelessness,AveCorrect,NumActions,AveResBored,AveResEngcon,AveResConf,AveResFrust,AveResOfftask,AveResGaming,action_num,skill,problemId,problemType,assignmentId,assistmentId,startTime,endTime,timeTaken,correct,original,hint,hintCount,hintTotal,scaffold,bottomHint,attemptCount,frIsHelpRequest,frPast5HelpRequest,frPast8HelpRequest,stlHintUsed,past8BottomOut,totalFrPercentPastWrong,totalFrPastWrongCount,frPast5WrongCount,frPast8WrongCount,totalFrTimeOnSkill,timeSinceSkill,frWorkingInSchool,totalFrAttempted,totalFrSkillOpportunities,responseIsFillIn,responseIsChosen,endsWithScaffolding,endsWithAutoScaffolding,frTimeTakenOnScaffolding,frTotalSkillOpportunitiesScaffolding,totalFrSkillOpportunitiesByScaffolding,frIsHelpRequestScaffolding,timeGreater5Secprev2wrong,sumRight,helpAccessUnder2Sec,timeGreater10SecAndNextActionRight,consecutiveErrorsInRow,sumTime3SDWhen3RowRight,sumTimePerSkill,totalTimeByPercentCorrectForskill,Prev5count,timeOver80,manywrong,confidence(BORED),confidence(CONCENTRATING),confidence(CONFUSED),confidence(FRUSTRATED),confidence(OFF TASK),confidence(GAMING),RES_BORED,RES_CONCENTRATING,RES_CONFUSED,RES_FRUSTRATED,RES_OFFTASK,RES_GAMING,Ln-1,Ln,MCAS,Enrolled,Selective,isSTEM
0,8,2,Male,2004-2005,0.352416,0.183276,0.483902,1056,0.208389,0.679126,0.115905,0.112408,0.156503,0.196561,9950,properties-of-geometric-figures,1118,textfieldquestion,20405010,104051118,1096470301,1096470350,49.0,0,1,1,1,1,0,0,1,1,0,0,0,0,0.0,0,0,0,0.0,0.0,1,0,0,0,0,0,0,0.0,0,0.0,0,0,0,0,0,0,0.0,49.0,0.000000,0,0,0,0.597865,0.234294,0.0000,0.0,0.838710,0.008522,0.376427,0.320317,0.000000,0.0,0.785585,0.000264,0.13,0.06119,45,0,0,NaN
1,8,2,Male,2004-2005,0.352416,0.183276,0.483902,1056,0.208389,0.679126,0.115905,0.112408,0.156503,0.196561,9951,properties-of-geometric-figures,1119,noprobtype,20405010,104051119,1096470350,1096470354,4.0,1,0,0,0,0,1,0,1,1,1,1,0,0,0.0,0,0,0,49.0,0.0,1,1,1,0,0,1,0,4.0,0,0.0,1,0,1,0,1,0,0.0,53.0,106.000000,1,0,0,0.355694,0.992585,0.9375,0.0,0.600000,0.047821,0.156027,0.995053,0.887452,0.0,0.468252,0.001483,0.06119,0.21351,45,0,0,NaN
2,8,2,Male,2004-2005,0.352416,0.183276,0.483902,1056,0.208389,0.679126,0.115905,0.112408,0.156503,0.196561,9952,sum-of-interior-angles-more-than-3-sides,1120,noprobtype,20405010,104051120,1096470354,1096470360,6.0,0,0,0,0,0,0,0,1,0,0,0,0,0,0.0,0,0,0,0.0,0.0,1,2,0,0,0,0,0,6.0,0,0.0,0,0,1,0,0,0,0.0,6.0,0.000000,2,0,0,0.355694,0.992585,0.9375,0.0,0.600000,0.047821,0.156027,0.995053,0.887452,0.0,0.468252,0.001483,0.116,0.033306,45,0,0,NaN
3,8,2,Male,2004-2005,0.352416,0.183276,0.483902,1056,0.208389,0.679126,0.115905,0.112408,0.156503,0.196561,9953,sum-of-interior-angles-more-than-3-sides,1120,noprobtype,20405010,104051120,1096470360,1096470378,18.0,0,0,0,0,0,0,0,2,0,0,0,0,0,0.0,1,0,0,0.0,0.0,1,3,1,0,0,0,0,6.0,1,0.0,0,0,1,0,0,1,0.0,24.0,0.000000,3,0,0,0.355694,0.617065,0.0000,0.0,0.204082,0.343996,0.156027,0.744520,0.000000,0.0,0.108417,0.010665,0.116,0.033306,45,0,0,NaN
4,8,2,Male,2004-2005,0.352416,0.183276,0.483902,1056,0.208389,0.679126,0.115905,0.112408,0.156503,0.196561,9954,sum-of-interior-angles-more-than-3-sides,1121,noprobtype,20405010,104051121,1096470378,1096470380,2.0,1,0,0,0,1,0,0,1,0,0,0,0,0,1.0,1,1,1,6.0,0.0,1,3,1,0,0,0,0,2.0,1,1.0,0,0,2,0,1,0,0.0,26.0,77.999999,4,0,1,0.355694,0.617065,0.0000,0.0,0.204082,0.343996,0.156027,0.744520,0.000000,0.0,0.108417,0.010665,0.033306,0.118386,45,0,0,NaN

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 942816 entries, 0 to 942815
Data columns (total 82 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   studentId                               942816 non-null  int64
 1   MiddleSchoolId                          942816 non-null  int64
 2   InferredGender                          769160 non-null  object
 3   SY ASSISTments Usage                    942816 non-null  object
 4   AveKnow                                 942816 non-null  float64
 5   AveCarelessness                         942816 non-null  float64
 6   AveCorrect                              942816 non-null  float64
 7   NumActions                              942816 non-null  int64
 8   AveResBored                             942816 non-null  float64
 9   AveResEngcon                            942816 non-null  float64
 10  AveResConf                              942816 non-null  float64
 11  AveResFrust                             942816 non-null  float64
 12  AveResOfftask                           942816 non-null  float64
 13  AveResGaming                            942816 non-null  float64
 14  action_num                              942816 non-null  int64
 15  skill                                   942816 non-null  object
 16  problemId                               942816 non-null  int64
 17  problemType                             942816 non-null  object
 18  assignmentId                            942816 non-null  int64
 19  assistmentId                            942816 non-null  int64
 20  startTime                               942816 non-null  int64
 21  endTime                                 942816 non-null  int64
 22  timeTaken                               942816 non-null  float64
 23  correct                                 942816 non-null  int64
 24  original                                942816 non-null  int64
 25  hint                                    942816 non-null  int64
 26  hintCount                               942816 non-null  int64
 27  hintTotal                               942816 non-null  int64
 28  scaffold                                942816 non-null  int64
 29  bottomHint                              942816 non-null  int64
 30  attemptCount                            942816 non-null  int64
 31  frIsHelpRequest                         942816 non-null  int64
 32  frPast5HelpRequest                      942816 non-null  int64
 33  frPast8HelpRequest                      942816 non-null  int64
 34  stlHintUsed                             942816 non-null  int64
 35  past8BottomOut                          942816 non-null  int64
 36  totalFrPercentPastWrong                 942816 non-null  float64
 37  totalFrPastWrongCount                   942816 non-null  int64
 38  frPast5WrongCount                       942816 non-null  int64
 39  frPast8WrongCount                       942816 non-null  int64
 40  totalFrTimeOnSkill                      942816 non-null  float64
 41  timeSinceSkill                          942816 non-null  float64
 42  frWorkingInSchool                       942816 non-null  int64
 43  totalFrAttempted                        942816 non-null  int64
 44  totalFrSkillOpportunities               942816 non-null  int64
 45  responseIsFillIn                        942816 non-null  int64
 46  responseIsChosen                        942816 non-null  int64
 47  endsWithScaffolding                     942816 non-null  int64
 48  endsWithAutoScaffolding                 942816 non-null  int64
 49  frTimeTakenOnScaffolding                942816 non-null  float64
 50  frTotalSkillOpportunitiesScaffolding    942816 non-null  int64
 51  totalFrSkillOpportunitiesByScaffolding  942816 non-null  float64
 52  frIsHelpRequestScaffolding              942816 non-null  int64
 53  timeGreater5Secprev2wrong               942816 non-null  int64
 54  sumRight                                942816 non-null  int64
 55  helpAccessUnder2Sec                     942816 non-null  int64
 56  timeGreater10SecAndNextActionRight      942816 non-null  int64
 57  consecutiveErrorsInRow                  942816 non-null  int64
 58  sumTime3SDWhen3RowRight                 942731 non-null  float64
 59  sumTimePerSkill                         942816 non-null  float64
 60  totalTimeByPercentCorrectForskill       942816 non-null  float64
 61  Prev5count                              942816 non-null  int64
 62  timeOver80                              942816 non-null  int64
 63  manywrong                               942816 non-null  int64
 64  confidence(BORED)                       942816 non-null  float64
 65  confidence(CONCENTRATING)               942816 non-null  float64
 66  confidence(CONFUSED)                    942816 non-null  float64
 67  confidence(FRUSTRATED)                  942816 non-null  float64
 68  confidence(OFF TASK)                    942816 non-null  float64
 69  confidence(GAMING)                      942816 non-null  float64
 70  RES_BORED                               942816 non-null  float64
 71  RES_CONCENTRATING                       942816 non-null  float64
 72  RES_CONFUSED                            942816 non-null  float64
 73  RES_FRUSTRATED                          942816 non-null  float64
 74  RES_OFFTASK                             942816 non-null  float64
 75  RES_GAMING                              942816 non-null  float64
 76  Ln-1                                    942816 non-null  object
 77  Ln                                      942816 non-null  object
 78  MCAS                                    942816 non-null  int64
 79  Enrolled                                942816 non-null  int64
 80  Selective                               942816 non-null  int64
 81  isSTEM                                  316974 non-null  float64
dtypes: float64(31), int64(45), object(6)
memory usage: 589.8+ MB

In [20]:
df.describe(include="all")

,studentId,MiddleSchoolId,InferredGender,SY ASSISTments Usage,AveKnow,AveCarelessness,AveCorrect,NumActions,AveResBored,AveResEngcon,AveResConf,AveResFrust,AveResOfftask,AveResGaming,action_num,skill,problemId,problemType,assignmentId,assistmentId,startTime,endTime,timeTaken,correct,original,hint,hintCount,hintTotal,scaffold,bottomHint,attemptCount,frIsHelpRequest,frPast5HelpRequest,frPast8HelpRequest,stlHintUsed,past8BottomOut,totalFrPercentPastWrong,totalFrPastWrongCount,frPast5WrongCount,frPast8WrongCount,totalFrTimeOnSkill,timeSinceSkill,frWorkingInSchool,totalFrAttempted,totalFrSkillOpportunities,responseIsFillIn,responseIsChosen,endsWithScaffolding,endsWithAutoScaffolding,frTimeTakenOnScaffolding,frTotalSkillOpportunitiesScaffolding,totalFrSkillOpportunitiesByScaffolding,frIsHelpRequestScaffolding,timeGreater5Secprev2wrong,sumRight,helpAccessUnder2Sec,timeGreater10SecAndNextActionRight,consecutiveErrorsInRow,sumTime3SDWhen3RowRight,sumTimePerSkill,totalTimeByPercentCorrectForskill,Prev5count,timeOver80,manywrong,confidence(BORED),confidence(CONCENTRATING),confidence(CONFUSED),confidence(FRUSTRATED),confidence(OFF TASK),confidence(GAMING),RES_BORED,RES_CONCENTRATING,RES_CONFUSED,RES_FRUSTRATED,RES_OFFTASK,RES_GAMING,Ln-1,Ln,MCAS,Enrolled,Selective,isSTEM
count,942816.000000,942816.000000,769160,942816,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,9.428160e+05,942816,942816.000000,942816,9.428160e+05,9.428160e+05,9.428160e+05,9.428160e+05,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,9.428160e+05,942816.000000,942816.000000,942816.000000,942816.000000,942816.0,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942731.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,9.428160e+05,942816.000000,942816.000000,942816.000000,942816.000000,942816.000000,9.428160e+05,942816.000000,942816.000000,942816.000000,942816.000000,942816.000,942816.000000,942816.000000,942816.000000,942816.000000,316974.000000
unique,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,113622.000,125282.000000,NaN,NaN,NaN,NaN
top,NaN,NaN,Male,2004-2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,noskill,NaN,textfieldquestion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.095,0.011664,NaN,NaN,NaN,NaN
freq,NaN,NaN,407637,544596,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78103,NaN,264399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4514.000,4634.000000,NaN,NaN,NaN,NaN
mean,3844.844105,2.515472,NaN,NaN,0.195155,0.109436,0.372681,869.850594,0.232949,0.658442,0.098940,0.131406,0.172212,0.192703,1.849329e+06,NaN,1899.719319,NaN,1.198773e+07,6.061572e+07,1.120793e+09,1.120793e+09,29.747869,0.372681,0.264214,0.331025,1.218490,1.953967,0.385732,0.062794,2.673605,0.268104,1.947322,2.575323,0.004012,0.241678,0.227882,1.988008,0.719380,0.944750,376.213405,4.850802e+05,0.974588,193.316005,8.381019,0.023131,0.0,0.636085,0.005724,24.060853,3.989371,1.036189,0.670047,0.045388,145.982059,0.055674,0.207414,0.155307,0.087042,601.665586,2166.143744,4.972689,0.081323,0.715638,0.436958,5.400894e-01,0.134450,0.164114,0.256006,0.337888,0.232949,6.584415e-01,0.098940,0.131406,0.172212,0.192703,NaN,NaN,-95.982302,0.641147,0.300434,0.204178
std,2250.484065,1.039785,NaN,NaN,0.116451,0.059952,0.107367,530.210725,0.030637,0.027440,0.034788,0.038875,0.057992,0.153455,1.726001e+06,NaN,2579.212724,NaN,1.434706e+07,5.128829e+07,1.940359e+07,1.940354e+07,72.019768,0.483519,0.440914,0.470582,1.980665,2.929242,0.486768,0.242592,2.929801,0.442972,1.712580,2.457799,0.063217,0.674613,0.271404,3.390149,0.832699,1.076276,689.302924,2.075599e+06,0.157373,164.898869,11.998292,0.150319,0.0,0.481125,0.075443,71.665655,6.581897,1.184489,0.470196,0.208155,124.342503,0.229291,0.405455,0.885692,1.619202,953.900687,4601.435964,0.315281,0.273331,0.451110,0.120751,1.830483e-01,0.292877,0.326057,0.213177,0.335292,0.116371,1.734275e-01,0.249505,0.300351,0.216997,0.340232,NaN,NaN,332.827628,0.479664,0.458447,0.403100
min,8.000000,1.000000,NaN,NaN,0.028057,0.007801,0.000000,2.000000,0.170871,0.403309,0.005075,0.000000,0.083167,0.001974,9.950000e+03,NaN,1.000000,NaN,2.000000e+00,5.000000e+00,1.095421e+09,1.095421e+09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-9.928014e+06,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-11.332080,0.000000,0.000000,0.000000,0.000000,0.000000,0.355694,6.500000e-07,0.000000,0.000000,0.000000,0.000039,0.156027,8.890000e-07,0.000000,0.000000,0.000000,0.000001,NaN,NaN,-999.000000,0.000000,0.000000,0.000000
25%,1952.000000,2.000000,NaN,NaN,0.110542,0.068760,0.294989,478.000000,0.209035,0.642060,0.076385,0.107278,0.131467,0.060724,7.221708e+05,NaN,721.000000,NaN,7.230000e+02,2.213000e+03,1.103136e+09,1.103136e+09,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,37.000000,0.000000e+00,1.000000,67.000000,2.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,50.000000,0.000000,0.000000,0.000000,0.000000,107.000000,189.736571,5.000000,0.000000,0.000000,0.355694,3.743169e-01,0.000000,0.000000,0.090909,0.047821,0.156027,5.117519e-01,0.000000,0.000000,0.048295,0.001483,NaN,NaN,14.000000,0.000000,0.000000,0.000000
50%,3766.000000,2.000000,NaN,NaN,0.159285,0.094513,0.345575,754.000000,0.230394,0.660669,0.096357,0.127504,0.159598,0.156245,9.578745e+05,NaN,1116.000000,NaN,2.040501e+07,1.040504e+08,1.112980e+09,1.112980e+09,11.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,2.000000,0.000000,2.000000,2.000000,0.000000,0.000000,0.166667,1.000000,1.000000,1.000000,140.000000,0.000000e+00,1.000000,151.000000,4.000000,0.000000,0.0,1.000000,0.000000,8.000000,2.000000,1.176471,1.000000,0.000000,113.000000,0.000000,0.000000,0.000000,0.000000,275.000000,840.000006,5.000000,0.000000,1.000000,0.355694,5.676439e-01,0.000000,0.000000,0.230769,0.186970,0.156027,7.115475e-01,0.000000,0.000000,0.122595,0.005797,NaN,NaN,23.000000,1.000000,0.000000,0.000000
75%,5781.000000,4.000000,NaN,NaN,0.247704,0.137316,0.428822,1151.000000,0.252082,0.676588,0.119282,0.150582,0.198533,0.298914,2.722813e+06,NaN,1419.000000,NaN,2.040510e+07,1.040511e+08,1.138371e+09,1.138371e+09,30.000000,1.000000,1.000000,1.000000,2.000000,3.000000,1.000000,0.000000,3.000000,1.000000,3.000000,4.000000,0.000000,0.000000,0.333333,2.000000,1.000000,1.000000,396.000000,8.000000e+00,1.000000,276.000000,10.000000,0.000000,0.0,1.000000,0.000000,23.000000,5.000000,1.656250,1.000000,0.000000,210.000000,0.000000,0.000000,0.000000,0.000000,669.000001,2404.499998,5.000000,0.000000,1.000000,0.597865,6.591692e-01,0.000000,0.091463,0.230769,0.614582,0.376427,7.726099e-01,0.000000,0.009561,0.122595,0.259648,NaN,NaN,34.000000,1.000000,1.000000,0.000000
max,7783.000000,4.000000,NaN,NaN,0.752498,0.430576,0.932990,3057.000000,0.440870,0.723990,0.402483,0.543463,0.837402,0.709200,6.355811e+06,NaN,22761.000000,NaN,1.000000e+09,1.040515e+08,1.180218e+09,1.180218e+09,9999.000000,1.000000,1.000000,1.000000,56.000000,56.000000,1.000000,1.000000,91.000000,1.000000,5.000000,8.000000,1.000000,8.000000,1.000000,73.000000,5.000000,8.000000,11663.000000,4.840000e+07,1.000000,1378.000000,221.000000,1.000000,0.0,1.000000,1.000000,9999.000000,105.000000,37.000000,1.000000,1.000000,962.000000,1.000000,1.000000,56.000000,92.709045,12459.000000,310590.000100,5.000000,1.000000,1.000000,0.680982,1.000000e+00,1.000000,1.000000,1.000000,0.999676,0.505313,1.000000e+00,1.000000,1.000000,1.000000,0.999377,NaN,NaN,54.000000,1.000000,1.000000,1.000000

🟦 Step 14 — Check Dataset Size
📖 Theory

Before cleaning, we should know how big the dataset is.

This tells us:

Number of students
Number of interactions
Memory usage

In [21]:
print("="*60)
print("Dataset Shape")
print("="*60)

print(f"Rows    : {df.shape[0]:,}")
print(f"Columns : {df.shape[1]}")

memory = df.memory_usage(deep=True).sum() / 1024**2

print(f"Memory Usage : {memory:.2f} MB")

============================================================
Dataset Shape
============================================================
Rows    : 942,816
Columns : 82
Memory Usage : 816.54 MB

🟦 Step 15 — Column Names
📖 Theory

Never engineer features without first understanding what exists.

In [22]:
columns = pd.DataFrame({
    "Column Number": range(1, len(df.columns)+1),
    "Column Name": df.columns
})

columns

    Column Number                             Column Name
0               1                               studentId
1               2                          MiddleSchoolId
2               3                          InferredGender
3               4                    SY ASSISTments Usage
4               5                                 AveKnow
5               6                         AveCarelessness
6               7                              AveCorrect
7               8                              NumActions
8               9                             AveResBored
9              10                            AveResEngcon
10             11                              AveResConf
11             12                             AveResFrust
12             13                           AveResOfftask
13             14                            AveResGaming
14             15                              action_num
15             16                                   skill
16             17                               problemId
17             18                             problemType
18             19                            assignmentId
19             20                            assistmentId
20             21                               startTime
21             22                                 endTime
22             23                               timeTaken
23             24                                 correct
24             25                                original
25             26                                    hint
26             27                               hintCount
27             28                               hintTotal
28             29                                scaffold
29             30                              bottomHint
30             31                            attemptCount
31             32                         frIsHelpRequest
32             33                      frPast5HelpRequest
33             34                      frPast8HelpRequest
34             35                             stlHintUsed
35             36                          past8BottomOut
36             37                 totalFrPercentPastWrong
37             38                   totalFrPastWrongCount
38             39                       frPast5WrongCount
39             40                       frPast8WrongCount
40             41                      totalFrTimeOnSkill
41             42                          timeSinceSkill
42             43                       frWorkingInSchool
43             44                        totalFrAttempted
44             45               totalFrSkillOpportunities
45             46                        responseIsFillIn
46             47                        responseIsChosen
47             48                     endsWithScaffolding
48             49                 endsWithAutoScaffolding
49             50                frTimeTakenOnScaffolding
50             51    frTotalSkillOpportunitiesScaffolding
51             52  totalFrSkillOpportunitiesByScaffolding
52             53              frIsHelpRequestScaffolding
53             54               timeGreater5Secprev2wrong
54             55                                sumRight
55             56                     helpAccessUnder2Sec
56             57      timeGreater10SecAndNextActionRight
57             58                  consecutiveErrorsInRow
58             59                 sumTime3SDWhen3RowRight
59             60                         sumTimePerSkill
60             61       totalTimeByPercentCorrectForskill
61             62                              Prev5count
62             63                              timeOver80
63             64                               manywrong
64             65                       confidence(BORED)
65             66               confidence(CONCENTRATING)
66             67                    confidence(CONFUSED)
67             68                  confidence(FRUSTRATED)
68             69                    confidence(OFF TASK)
69             70                      confidence(GAMING)
70             71                               RES_BORED
71             72                       RES_CONCENTRATING
72             73                            RES_CONFUSED
73             74                          RES_FRUSTRATED
74             75                             RES_OFFTASK
75             76                              RES_GAMING
76             77                                    Ln-1
77             78                                      Ln
78             79                                    MCAS
79             80                                Enrolled
80             81                               Selective
81             82                                  isSTEM

🟦 Step 16 — Missing Values
📖 Theory

Missing values are one of the biggest reasons ML models fail.

We won't remove anything yet.

First we inspect.

In [23]:
missing = pd.DataFrame({

    "Missing Count": df.isnull().sum(),

    "Missing %": (df.isnull().mean()*100).round(2)

})

missing = missing.sort_values(

    "Missing %",

    ascending=False

)

missing

                                        Missing Count  Missing %
isSTEM                                         625842      66.38
InferredGender                                 173656      18.42
sumTime3SDWhen3RowRight                            85       0.01
SY ASSISTments Usage                                0       0.00
MiddleSchoolId                                      0       0.00
AveCarelessness                                     0       0.00
AveCorrect                                          0       0.00
NumActions                                          0       0.00
AveKnow                                             0       0.00
AveResEngcon                                        0       0.00
AveResConf                                          0       0.00
AveResFrust                                         0       0.00
AveResOfftask                                       0       0.00
AveResGaming                                        0       0.00
action_num                                          0       0.00
skill                                               0       0.00
AveResBored                                         0       0.00
studentId                                           0       0.00
problemType                                         0       0.00
problemId                                           0       0.00
assignmentId                                        0       0.00
assistmentId                                        0       0.00
timeTaken                                           0       0.00
correct                                             0       0.00
startTime                                           0       0.00
endTime                                             0       0.00
hintCount                                           0       0.00
hintTotal                                           0       0.00
scaffold                                            0       0.00
bottomHint                                          0       0.00
attemptCount                                        0       0.00
frIsHelpRequest                                     0       0.00
original                                            0       0.00
hint                                                0       0.00
stlHintUsed                                         0       0.00
past8BottomOut                                      0       0.00
totalFrPercentPastWrong                             0       0.00
totalFrPastWrongCount                               0       0.00
frPast5WrongCount                                   0       0.00
frPast8WrongCount                                   0       0.00
totalFrTimeOnSkill                                  0       0.00
timeSinceSkill                                      0       0.00
frWorkingInSchool                                   0       0.00
totalFrAttempted                                    0       0.00
totalFrSkillOpportunities                           0       0.00
responseIsFillIn                                    0       0.00
responseIsChosen                                    0       0.00
endsWithScaffolding                                 0       0.00
frPast5HelpRequest                                  0       0.00
frPast8HelpRequest                                  0       0.00
frTimeTakenOnScaffolding                            0       0.00
endsWithAutoScaffolding                             0       0.00
frIsHelpRequestScaffolding                          0       0.00
frTotalSkillOpportunitiesScaffolding                0       0.00
sumRight                                            0       0.00
helpAccessUnder2Sec                                 0       0.00
timeGreater10SecAndNextActionRight                  0       0.00
totalFrSkillOpportunitiesByScaffolding              0       0.00
consecutiveErrorsInRow                              0       0.00
sumTimePerSkill                                     0       0.00
totalTimeByPercentCorrectForskill                   0       0.00
Prev5count                                          0       0.00
timeOver80                                          0       0.00
manywrong                                           0       0.00
confidence(BORED)                                   0       0.00
timeGreater5Secprev2wrong                           0       0.00
confidence(CONCENTRATING)                           0       0.00
confidence(CONFUSED)                                0       0.00
confidence(OFF TASK)                                0       0.00
confidence(FRUSTRATED)                              0       0.00
RES_BORED                                           0       0.00
RES_CONCENTRATING                                   0       0.00
RES_CONFUSED                                        0       0.00
confidence(GAMING)                                  0       0.00
RES_FRUSTRATED                                      0       0.00
RES_OFFTASK                                         0       0.00
Ln-1                                                0       0.00
RES_GAMING                                          0       0.00
Ln                                                  0       0.00
MCAS                                                0       0.00
Enrolled                                            0       0.00
Selective                                           0       0.00

🟦 Step 17 — Duplicate Rows
📖 Theory

Duplicate interactions create bias.

In [24]:
duplicates = df.duplicated().sum()

print(f"Duplicate Rows : {duplicates:,}")

Duplicate Rows : 0

🟦 Step 18 — Data Types
📖 Theory

Understanding data types helps us plan preprocessing.

In [25]:
datatype_summary = pd.DataFrame({

    "Column": df.columns,

    "Datatype": df.dtypes

})

datatype_summary

,Column,Datatype
studentId,studentId,int64
MiddleSchoolId,MiddleSchoolId,int64
InferredGender,InferredGender,object
SY ASSISTments Usage,SY ASSISTments Usage,object
AveKnow,AveKnow,float64
AveCarelessness,AveCarelessness,float64
AveCorrect,AveCorrect,float64
NumActions,NumActions,int64
AveResBored,AveResBored,float64
AveResEngcon,AveResEngcon,float64
AveResConf,AveResConf,float64
AveResFrust,AveResFrust,float64
AveResOfftask,AveResOfftask,float64
AveResGaming,AveResGaming,float64
action_num,action_num,int64
skill,skill,object
problemId,problemId,int64
problemType,problemType,object
assignmentId,assignmentId,int64
assistmentId,assistmentId,int64
startTime,startTime,int64
endTime,endTime,int64
timeTaken,timeTaken,float64
correct,correct,int64
original,original,int64
hint,hint,int64
hintCount,hintCount,int64
hintTotal,hintTotal,int64
scaffold,scaffold,int64
bottomHint,bottomHint,int64
attemptCount,attemptCount,int64
frIsHelpRequest,frIsHelpRequest,int64
frPast5HelpRequest,frPast5HelpRequest,int64
frPast8HelpRequest,frPast8HelpRequest,int64
stlHintUsed,stlHintUsed,int64
past8BottomOut,past8BottomOut,int64
totalFrPercentPastWrong,totalFrPercentPastWrong,float64
totalFrPastWrongCount,totalFrPastWrongCount,int64
frPast5WrongCount,frPast5WrongCount,int64
frPast8WrongCount,frPast8WrongCount,int64
totalFrTimeOnSkill,totalFrTimeOnSkill,float64
timeSinceSkill,timeSinceSkill,float64
frWorkingInSchool,frWorkingInSchool,int64
totalFrAttempted,totalFrAttempted,int64
totalFrSkillOpportunities,totalFrSkillOpportunities,int64
responseIsFillIn,responseIsFillIn,int64
responseIsChosen,responseIsChosen,int64
endsWithScaffolding,endsWithScaffolding,int64
endsWithAutoScaffolding,endsWithAutoScaffolding,int64
frTimeTakenOnScaffolding,frTimeTakenOnScaffolding,float64
frTotalSkillOpportunitiesScaffolding,frTotalSkillOpportunitiesScaffolding,int64
totalFrSkillOpportunitiesByScaffolding,totalFrSkillOpportunitiesByScaffolding,float64
frIsHelpRequestScaffolding,frIsHelpRequestScaffolding,int64
timeGreater5Secprev2wrong,timeGreater5Secprev2wrong,int64
sumRight,sumRight,int64
helpAccessUnder2Sec,helpAccessUnder2Sec,int64
timeGreater10SecAndNextActionRight,timeGreater10SecAndNextActionRight,int64
consecutiveErrorsInRow,consecutiveErrorsInRow,int64
sumTime3SDWhen3RowRight,sumTime3SDWhen3RowRight,float64
sumTimePerSkill,sumTimePerSkill,float64
totalTimeByPercentCorrectForskill,totalTimeByPercentCorrectForskill,float64
Prev5count,Prev5count,int64
timeOver80,timeOver80,int64
manywrong,manywrong,int64
confidence(BORED),confidence(BORED),float64
confidence(CONCENTRATING),confidence(CONCENTRATING),float64
confidence(CONFUSED),confidence(CONFUSED),float64
confidence(FRUSTRATED),confidence(FRUSTRATED),float64
confidence(OFF TASK),confidence(OFF TASK),float64
confidence(GAMING),confidence(GAMING),float64
RES_BORED,RES_BORED,float64
RES_CONCENTRATING,RES_CONCENTRATING,float64
RES_CONFUSED,RES_CONFUSED,float64
RES_FRUSTRATED,RES_FRUSTRATED,float64
RES_OFFTASK,RES_OFFTASK,float64
RES_GAMING,RES_GAMING,float64
Ln-1,Ln-1,object
Ln,Ln,object
MCAS,MCAS,int64
Enrolled,Enrolled,int64
Selective,Selective,int64
isSTEM,isSTEM,float64

🟦 Step 19 — Timestamp Detection
📖 Theory

Knowledge Decay depends on time.

So timestamps are the most important columns.

Let's identify them.

In [26]:
time_columns = [

    col

    for col in df.columns

    if "time" in col.lower()

    or "date" in col.lower()

]

print(time_columns)

['startTime', 'endTime', 'timeTaken', 'totalFrTimeOnSkill', 'timeSinceSkill', 'frTimeTakenOnScaffolding', 'timeGreater5Secprev2wrong', 'timeGreater10SecAndNextActionRight', 'sumTime3SDWhen3RowRight', 'sumTimePerSkill', 'totalTimeByPercentCorrectForskill', 'timeOver80']

🟦 Step 20 — Convert Timestamp Columns
note converting anything we remove the code here !!!!!!!!!!
just inspect.

this is inspection block

In [27]:
print("="*60)
print("Time Feature Inspection")
print("="*60)

time_cols = [
    c for c in df.columns
    if "time" in c.lower()
]

for col in time_cols:
    print(f"\n{col}")
    print(df[col].head())
    print(df[col].dtype)

============================================================
Time Feature Inspection
============================================================

startTime
0    1096470301
1    1096470350
2    1096470354
3    1096470360
4    1096470378
Name: startTime, dtype: int64
int64

endTime
0    1096470350
1    1096470354
2    1096470360
3    1096470378
4    1096470380
Name: endTime, dtype: int64
int64

timeTaken
0    49.0
1     4.0
2     6.0
3    18.0
4     2.0
Name: timeTaken, dtype: float64
float64

totalFrTimeOnSkill
0     0.0
1    49.0
2     0.0
3     0.0
4     6.0
Name: totalFrTimeOnSkill, dtype: float64
float64

timeSinceSkill
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: timeSinceSkill, dtype: float64
float64

frTimeTakenOnScaffolding
0    0.0
1    4.0
2    6.0
3    6.0
4    2.0
Name: frTimeTakenOnScaffolding, dtype: float64
float64

timeGreater5Secprev2wrong
0    0
1    0
2    0
3    0
4    0
Name: timeGreater5Secprev2wrong, dtype: int64
int64

timeGreater10SecAndNextActionRight
0    0
1    1
2    0
3    0
4    1
Name: timeGreater10SecAndNextActionRight, dtype: int64
int64

sumTime3SDWhen3RowRight
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: sumTime3SDWhen3RowRight, dtype: float64
float64

sumTimePerSkill
0    49.0
1    53.0
2     6.0
3    24.0
4    26.0
Name: sumTimePerSkill, dtype: float64
float64

totalTimeByPercentCorrectForskill
0      0.000000
1    106.000000
2      0.000000
3      0.000000
4     77.999999
Name: totalTimeByPercentCorrectForskill, dtype: float64
float64

timeOver80
0    0
1    0
2    0
3    0
4    0
Name: timeOver80, dtype: int64
int64

In [28]:
print(df["startTime"].head())
print(df["endTime"].head())
print(df["timeTaken"].head())

0    1096470301
1    1096470350
2    1096470354
3    1096470360
4    1096470378
Name: startTime, dtype: int64
0    1096470350
1    1096470354
2    1096470360
3    1096470378
4    1096470380
Name: endTime, dtype: int64
0    49.0
1     4.0
2     6.0
3    18.0
4     2.0
Name: timeTaken, dtype: float64

🟦 Step 21 — Basic Dataset Summary

In [29]:
summary = {

    "Rows": len(df),

    "Columns": len(df.columns),

    "Numerical Columns": len(df.select_dtypes(include="number").columns),

    "Categorical Columns": len(df.select_dtypes(include="object").columns),

    "Datetime Columns": len(df.select_dtypes(include="datetime").columns),

    "Duplicate Rows Removed": duplicates

}

pd.DataFrame(summary.items(),

             columns=["Metric","Value"])

                   Metric   Value
0                    Rows  942816
1                 Columns      82
2       Numerical Columns      76
3     Categorical Columns       6
4        Datetime Columns       0
5  Duplicate Rows Removed       0

🟦 Step 22 — Save Interim Dataset

In [30]:
import os

os.makedirs("Data/Interim",

            exist_ok=True)

In [ ]:
df.to_csv(

    "Data/Interim/interactions_clean.csv",

    index=False

)

print("Dataset Saved Successfully")

🟦 Step 23 — Data Quality Report

In [ ]:
quality_report = pd.DataFrame({
    "Metric": [
        "Total Rows",
        "Total Columns",
        "Missing Cells",
        "Duplicate Rows",
        "Memory (MB)"
    ],
    "Value": [
        len(df),
        len(df.columns),
        df.isnull().sum().sum(),
        duplicates,
        round(df.memory_usage(deep=True).sum() / (1024**2), 2)
    ]
})

quality_report

In [ ]:
os.makedirs("Reports", exist_ok=True)

quality_report.to_csv(
    "Reports/data_quality_report.csv",
    index=False
)

print("Data Quality Report Saved")